### ISSUE TITLE
make_cdn_cia - Receive 'Segmentation fault: 11' 

### ISSUE THREAD

**Issue by llakssz** [ctrdev/ctrsdk#3]
Many times I receive a segmentation fault when running make_cdn_cia with many content files.
Here is the lldb output, I am not sure if it will be helpful - if not please tell me if gdb would give better information, or any other way I can help. (add printouts in the code etc, to see where it crashes)
Thank again for the hard work.

![mcc3lldb](https://cloud.githubusercontent.com/assets/10378832/5849769/189ab5d0-a225-11e4-9a46-0f08bba979f1.png)

**Comment by 173210** [comment]
Can you get stack trace(back trace)?

**Comment by 173210** [comment]
By the way, you may as well use debugger as debug with printf. It's useful for you even if you can't read assembly.

**Comment by llakssz** [comment]
Does this help? I can do more, I'm happy to help.

![xcodedebugmcc](https://cloud.githubusercontent.com/assets/10378832/5850679/2e85fa5c-a235-11e4-9d6a-4da005413964.png)

**Comment by 173210** [comment]
It may be fixed with commit fce2b2f8ed4a5bce931bfeef285a21cb630419d8

**Comment by llakssz** [comment]
Thank you, but I still get the same segmentation fault.
Would getting the stack/back trace help more?

![xcodemcc4](https://cloud.githubusercontent.com/assets/10378832/5852290/329d062a-a24f-11e4-9893-10d4d1c3afe7.png)

(Also, int write_content_data() in cia.c needs a 'return 0;')
Thank you again.

**Comment by 173210** [comment]
Well, I think the design of this program is not proper.
It's very troublesome to fix it.

**Comment by llakssz** [comment]
I understand, it is not your program.
Thank you for fixing it so far. If you cannot/do not want to fix it more I understand.

**Comment by 173210** [comment]
It may be fixed with commit 976c34d034840800ebb96a009838f23a03f61b92.
Now you can say goodbye for crappy cia.c.

**Comment by llakssz** [comment]
Wow that was a big re-write! Very cool! Thank you so much!
But, it seems the program has a problem now.
The cia fails to generate.
You can see the output in the debug console.
With an older build, the cia is created fine.

![xcodemcc6](https://cloud.githubusercontent.com/assets/10378832/5868006/992b5768-a2de-11e4-9a24-d7020fa4d65a.png)

**Comment by 173210** [comment]
Check the latest commit.
It makes easy to debug.

On 2015年1月23日 10:10:58 JST, llakssz <notifications@github.com> wrote:
>Wow that was a big re-write! Very cool! Thank you so much!
>But, it seems the program has a problem now.
>The cia fails to generate.
>You can see the output in the debug console.
>With an older build, the cia is created fine.
>
>![xcodemcc6](https://cloud.githubusercontent.com/assets/10378832/5868006/992b5768-a2de-11e4-9a24-d7020fa4d65a.png)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71131463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
Great, thank you.
in main.c - it keeps going into this:
if(tik_context.result != 0 || tmd_context.result != 0){

The tmd result is 0, but the tik result is x80.
As soon as the tmd_context is created, the result is 0. (and if a problem the result would become not 0)
But for tik_context, the result is x80 at the very beginning when it is created.
The sig type checks are ok, process_tik() does not return early, I think.

![xcodemcc7](https://cloud.githubusercontent.com/assets/10378832/5868930/203ab6b0-a2ec-11e4-84ee-ea7d9fc7a448.png)

**Comment by 173210** [comment]
I fixed the problem.

On 2015年1月23日 11:39:46 JST, llakssz <notifications@github.com> wrote:
>
>Great, thank you.
>in main.c - it keeps going into this:
>if(tik_context.result != 0 || tmd_context.result != 0){
>
>The tmd result is 0, but the tik result is x80.
>As soon as the tmd_context is created, the result is 0. (and if a
>problem the result would become not 0)
>But for tik_context, the result is x80 at the very beginning when it is
>created.
>The sig type checks are ok, process_tik() does not return early, I
>think.
>
>![xcodemcc7](https://cloud.githubusercontent.com/assets/10378832/5868930/203ab6b0-a2ec-11e4-84ee-ea7d9fc7a448.png)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71139054

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
Ok thank you. Now, I see in write_cia_header()
The codes is returning IO_FAIL..., the CIA will not build.

if (fwrite(&hdr, sizeof(hdr), 1, fp) != sizeof(hdr))
	return IO_FAIL;

**Comment by 173210** [comment]
fixed it.

On 2015年1月23日 12:57:41 JST, llakssz <notifications@github.com> wrote:
>Ok thank you. Now, I see in write_cia_header()
>The codes is returning IO_FAIL..., the CIA will not build.
>
>if (fwrite(&hdr, sizeof(hdr), 1, fp) != sizeof(hdr))
>	return IO_FAIL;
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71144381

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
Thank you!
the end of write_cia_header() returns IO_FAIL?, not 0?
and now, in write_cert_chain() - there is a problem, it returns IO_FAIL;
if (fseek(tmd->fp, tmd->cert.offset[0], SEEK_SET) != tmd->cert.offset[0])

**Comment by 173210** [comment]
fixed it.

On 2015年1月23日 13:39:52 JST, llakssz <notifications@github.com> wrote:
>Thank you!
>the end of write_cia_header() returns IO_FAIL?, not 0?
>and now, in write_cert_chain() - there is a problem, it returns
>IO_FAIL;
>if (fseek(tmd->fp, tmd->cert.offset[0], SEEK_SET) !=
>tmd->cert.offset[0])
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71146794

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
Thanks again, yes, that problem is fixed.
Now, in write_content(), I keep getting the error 'content cannot be opened'
Content is always NULL.

**Comment by 173210** [comment]
Can you get content id?

On 2015年1月23日 14:42:49 JST, llakssz <notifications@github.com> wrote:
>Thanks again, yes, that problem is fixed.
>Now, in write_content(), I keep getting the error 'content cannot be
>opened'
>Content is always NULL.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71150265

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
The output is [!] Content: '00000000' could not be opened
The very first content I think.

**Comment by 173210** [comment]
Do you have content '00000000'?
I guess not and the id is wrong.

On 2015年1月23日 14:56:32 JST, llakssz <notifications@github.com> wrote:
>The output is [!] Content: '00000000' could not be opened
>The very first content I think.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ctrdev/ctrsdk/issues/3#issuecomment-71151048

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llakssz** [comment]
I do have content 00000000.
The ID is correct, the hash, size...
Maybe I can send you some files to test with?

**Comment by 173210** [comment]
No, I don't have time to test. I updated the code. Try with the latest one.

**Comment by 173210** [comment]
Ok, I found a problem. I'm fixing it...
https://github.com/ctrdev/ctrsdk/blob/master/tools/make_cdn_cia/main.c#L92

**Comment by 173210** [comment]
fixed.

**Comment by llakssz** [comment]
Thank you for the fix!
On mac, I had a problem including endian.h, I had to change it to machine/endian.h. - Then, I still got build errors. I fixed it by using this: https://gist.github.com/panzi/6856583 - it seems very useful.
I do not believe portable_endian.h causing the next problem...:
[!] One or both of the signatures in the CETK 'Cert Chain' are unrecognised
get_sig_size() is not returning the value is should be, it returns ERR_UNRECOGNISED_SIG.

**Comment by 173210** [comment]
Try with the latest one.
I added byte-swap functions for GCC, ICC, and VC++. I think it will work also on clang.
And I updated get_sig_size and get_cert_size.

**Comment by llakssz** [comment]
I need #include <stdint.h>, otherwise I get 'unknown type name 'uint32_t'''.
After including it, I then get a linker error:
Undefined symbols for architecture x86_64:
  "_be64toh", referenced from:
      _generate_cia in cia.o
I am not sure how to fix that.
Again, thank you for your time and effort.

**Comment by 173210** [comment]
I fixed some bugs.
Well, I thought 3DSGuy is a stupid guy at first, but his newer work, makerom is very easy to read and it helps me to fix bugs in this program.
This program is almost made by 3DSGuy.

**Comment by llakssz** [comment]
Thanks again.
Good that makerom's source helps.
But, I still get an error when I try to compile (osx)
Undefined symbols for architecture x86_64:
  "_be64toh", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64

**Comment by 173210** [comment]
Which compiler are you using?
I think you can confirm that with "gcc -v"

**Comment by llakssz** [comment]
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.10.0 -o make_cdn_cia main.o cia.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_be64toh", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64

**Comment by 173210** [comment]
Well, clang supports __builtin_bswap* since 2 years ago. I have no idea why it won't work on your machine...
http://llvm.org/klaus/clang/commit/d190057934331390ff67ebf51d66186dd5e392f0/
http://llvm.org/klaus/clang/commit/df4852ac816e6050d53b808b86d7c1c9738eb99e/

**Comment by llakssz** [comment]
Do you think this is a problem? (-std=gnu99)
http://www.reddit.com/r/programming/comments/248gzy/portable_endianh/ch4m273

**Comment by 173210** [comment]
I don't think so if you are using the latest Makefile without -std option.
But I think you should do what you can do. I can't test that because I don't have osx environment.

**Comment by 173210** [comment]
I opened issue #4.
